package edu.ku.brc.specify.datamodel;

import java.util.*;




/**
 * AttachmentGroup generated by hbm2java
 */
public class AttachmentGroup  implements java.io.Serializable {

    // Fields    

     private Long attachmentGroupID;
     private String name;
     private String remarks;
     private Date timestampCreated;
     private Date timestampModified;
     private String lastEditedBy;
     private Set<Attachment> attachments;
     private Agent createdByAgent;
     private Set<Agent> agents;
     private Set<CollectionObject> collectionObjects;
     private Set<CollectingEvent> collectingEvents;
     private Set<Loan> loans;
     private Set<Locality> localities;
     private Set<Permit> permits;
     private Set<Preparation> preparations;
     private Set<Taxon> taxonomy;


    // Constructors

    /** default constructor */
    public AttachmentGroup()
    {
        // do nothing
    }
    
    /** constructor with id */
    public AttachmentGroup(Long attachmentGroupID) {
        this.attachmentGroupID = attachmentGroupID;
    }
   
    public void initialize()
    {
        attachmentGroupID = null;
        name = null;
        remarks = null;
        timestampCreated = null;
        timestampModified = null;
        lastEditedBy = null;
        attachments = null;
        createdByAgent = null;
        agents = new HashSet<Agent>();
        collectionObjects = new HashSet<CollectionObject>();
        collectingEvents = new HashSet<CollectingEvent>();
        loans = new HashSet<Loan>();
        localities = new HashSet<Locality>();
        permits = new HashSet<Permit>();
        preparations = new HashSet<Preparation>();
        taxonomy = new HashSet<Taxon>();
    }
    

    // Property accessors

    /**
     * 
     */
    public Long getAttachmentGroupID() {
        return this.attachmentGroupID;
    }
    
    public void setAttachmentGroupID(Long attachmentGroupID) {
        this.attachmentGroupID = attachmentGroupID;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * 
     */
    public Date getTimestampCreated() {
        return this.timestampCreated;
    }
    
    public void setTimestampCreated(Date timestampCreated) {
        this.timestampCreated = timestampCreated;
    }

    /**
     * 
     */
    public Date getTimestampModified() {
        return this.timestampModified;
    }
    
    public void setTimestampModified(Date timestampModified) {
        this.timestampModified = timestampModified;
    }

    /**
     * 
     */
    public String getLastEditedBy() {
        return this.lastEditedBy;
    }
    
    public void setLastEditedBy(String lastEditedBy) {
        this.lastEditedBy = lastEditedBy;
    }

    /**
     * 
     */
    public Set<Attachment> getAttachments() {
        return this.attachments;
    }
    
    public void setAttachments(Set<Attachment> attachments) {
        this.attachments = attachments;
    }

    /**
     * 
     */
    public Agent getCreatedByAgent() {
        return this.createdByAgent;
    }
    
    public void setCreatedByAgent(Agent createdByAgent) {
        this.createdByAgent = createdByAgent;
    }

    /**
     * 
     */
    public Set<Agent> getAgents() {
        return this.agents;
    }
    
    public void setAgents(Set<Agent> agents) {
        this.agents = agents;
    }

    /**
     * 
     */
    public Set<CollectionObject> getCollectionObjects() {
        return this.collectionObjects;
    }
    
    public void setCollectionObjects(Set<CollectionObject> collectionObjects) {
        this.collectionObjects = collectionObjects;
    }

    /**
     * 
     */
    public Set<CollectingEvent> getCollectingEvents() {
        return this.collectingEvents;
    }
    
    public void setCollectingEvents(Set<CollectingEvent> collectingEvents) {
        this.collectingEvents = collectingEvents;
    }

    /**
     * 
     */
    public Set<Loan> getLoans() {
        return this.loans;
    }
    
    public void setLoans(Set<Loan> loans) {
        this.loans = loans;
    }

    /**
     * 
     */
    public Set<Locality> getLocalities() {
        return this.localities;
    }
    
    public void setLocalities(Set<Locality> localities) {
        this.localities = localities;
    }

    /**
     * 
     */
    public Set<Permit> getPermits() {
        return this.permits;
    }
    
    public void setPermits(Set<Permit> permits) {
        this.permits = permits;
    }

    /**
     * 
     */
    public Set<Preparation> getPreparations() {
        return this.preparations;
    }
    
    public void setPreparations(Set<Preparation> preparations) {
        this.preparations = preparations;
    }

    /**
     * 
     */
    public Set<Taxon> getTaxonomy() {
        return this.taxonomy;
    }
    
    public void setTaxonomy(Set<Taxon> taxonomy) {
        this.taxonomy = taxonomy;
    }




}