/**
 * Copyright (C) 2006  The University of Kansas
 *
 * [INSERT KU-APPROVED LICENSE TEXT HERE]
 * 
 */
package edu.ku.brc.specify.datamodel;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * AttachmentMetadata generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicInsert=true, dynamicUpdate=true)
@Table(name = "attachmentmetadata")
public class AttachmentMetadata extends DataModelObjBase implements java.io.Serializable
{

    // Fields

    private Long       attachmentMetadataID;
    private String     name;
    private String     value;
    private Attachment attachment;

    // Constructors

    /** default constructor */
    public AttachmentMetadata()
    {
        // do nothing
    }

    /** constructor with id */
    public AttachmentMetadata(Long attachmentMetadataID)
    {
        this.attachmentMetadataID = attachmentMetadataID;
    }

    // Initializer
    @Override
    public void initialize()
    {
        super.init();
        attachmentMetadataID = null;
        name = null;
        value = null;
        attachment = null;
    }
    // End Initializer
    
    // Property accessors

    /**
     * 
     */
    @Id
    @GeneratedValue
    @Column(name = "AttachmentMetadataID", unique = false, nullable = false, insertable = true, updatable = true)
    public Long getAttachmentMetadataID()
    {
        return this.attachmentMetadataID;
    }

    public void setAttachmentMetadataID(Long attachmentMetadataID)
    {
        this.attachmentMetadataID = attachmentMetadataID;
    }

    @Transient
    @Override
    public Long getId()
    {
        return attachmentMetadataID;
    }

    /* (non-Javadoc)
     * @see edu.ku.brc.ui.forms.FormDataObjIFace#getDataClass()
     */
    @Transient
    @Override
    public Class<?> getDataClass()
    {
        return AttachmentMetadata.class;
    }

    /**
     * 
     */
    @Column(name = "Name", unique = false, nullable = true, insertable = true, updatable = true, length = 64)
    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    /**
     * 
     */
    @Column(name = "Value", unique = false, nullable = true, insertable = true, updatable = true)
    public String getValue()
    {
        return this.value;
    }

    public void setValue(String value)
    {
        this.value = value;
    }

    /**
     * 
     */
    @ManyToOne(cascade = {}, fetch = FetchType.LAZY)
    @JoinColumn(name = "AttachmentID", unique = false, nullable = true, insertable = true, updatable = true)
    public Attachment getAttachment()
    {
        return this.attachment;
    }

    public void setAttachment(Attachment attachment)
    {
        this.attachment = attachment;
    }

    /* (non-Javadoc)
     * @see edu.ku.brc.ui.forms.FormDataObjIFace#getTableId()
     */
    @Override
    @Transient
    public Integer getTableId()
    {
        return 42;
    }

}
