package edu.ku.brc.specify.datamodel;


/**
 * AttachmentMetadata generated by hbm2java
 */
public class AttachmentMetadata extends DataModelObjBase implements java.io.Serializable
{

    // Fields

    private Long       attachmentMetadataID;
    private String     name;
    private String     value;
    private Attachment attachment;

    // Constructors

    /** default constructor */
    public AttachmentMetadata()
    {
        // do nothing
    }

    /** constructor with id */
    public AttachmentMetadata(Long attachmentMetadataID)
    {
        this.attachmentMetadataID = attachmentMetadataID;
    }

    // Initializer
    @Override
    public void initialize()
    {
        attachmentMetadataID = null;
        name = null;
        value = null;
        attachment = null;
    }
    // End Initializer
    
    // Property accessors

    /**
     * 
     */
    public Long getAttachmentMetadataID()
    {
        return this.attachmentMetadataID;
    }

    public void setAttachmentMetadataID(Long attachmentMetadataID)
    {
        this.attachmentMetadataID = attachmentMetadataID;
    }

    /**
     * 
     */
    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    /**
     * 
     */
    public String getValue()
    {
        return this.value;
    }

    public void setValue(String value)
    {
        this.value = value;
    }

    /**
     * 
     */
    public Attachment getAttachment()
    {
        return this.attachment;
    }

    public void setAttachment(Attachment attachment)
    {
        this.attachment = attachment;
    }

    /* (non-Javadoc)
     * @see edu.ku.brc.ui.forms.FormDataObjIFace#getTableId()
     */
    @Override
    public Integer getTableId()
    {
        return 42;
    }

}
