package edu.ku.brc.specify.datamodel;

import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Attachment generated by hbm2java
 */
public class Attachment implements java.io.Serializable
{
    // Fields

    private Long                    attachmentID;
    private String                  mimeType;
    private String                  origFilename;
    private Calendar                fileCreatedDate;
    private String                  remarks;
    private String                  attachmentLocation;
    private Date                    timestampCreated;
    private Date                    timestampModified;
    private String                  lastEditedBy;
    private Set<AttachmentGroup>    attachmentGroups;
    private Set<AttachmentMetadata> metadata;

    // Constructors

    /** default constructor */
    public Attachment()
    {
        // do nothing
    }

    /** constructor with id */
    public Attachment(Long attachmentID)
    {
        this.attachmentID = attachmentID;
    }
    
    public void initialize()
    {
        attachmentID = null;
        mimeType = null;
        origFilename = null;
        fileCreatedDate = null;
        remarks = null;
        attachmentLocation = null;
        timestampCreated = null;
        timestampModified = null;
        lastEditedBy = null;
        attachmentGroups = new HashSet<AttachmentGroup>();
        metadata = new HashSet<AttachmentMetadata>();
    }

    // Property accessors

    /**
     * 
     */
    public Long getAttachmentID()
    {
        return this.attachmentID;
    }

    public void setAttachmentID(Long attachmentID)
    {
        this.attachmentID = attachmentID;
    }

    /**
     * 
     */
    public String getMimeType()
    {
        return this.mimeType;
    }

    public void setMimeType(String mimeType)
    {
        this.mimeType = mimeType;
    }

    /**
     * 
     */
    public String getOrigFilename()
    {
        return this.origFilename;
    }

    public void setOrigFilename(String origFilename)
    {
        this.origFilename = origFilename;
    }

    /**
     * 
     */
    public Calendar getFileCreatedDate()
    {
        return this.fileCreatedDate;
    }

    public void setFileCreatedDate(Calendar fileCreatedDate)
    {
        this.fileCreatedDate = fileCreatedDate;
    }

    /**
     * 
     */
    public String getRemarks()
    {
        return this.remarks;
    }

    public void setRemarks(String remarks)
    {
        this.remarks = remarks;
    }

    /**
     * 
     */
    public String getAttachmentLocation()
    {
        return this.attachmentLocation;
    }

    public void setAttachmentLocation(String attachmentLocation)
    {
        this.attachmentLocation = attachmentLocation;
    }

    /**
     * 
     */
    public Date getTimestampCreated()
    {
        return this.timestampCreated;
    }

    public void setTimestampCreated(Date timestampCreated)
    {
        this.timestampCreated = timestampCreated;
    }

    /**
     * 
     */
    public Date getTimestampModified()
    {
        return this.timestampModified;
    }

    public void setTimestampModified(Date timestampModified)
    {
        this.timestampModified = timestampModified;
    }

    /**
     * 
     */
    public String getLastEditedBy()
    {
        return this.lastEditedBy;
    }

    public void setLastEditedBy(String lastEditedBy)
    {
        this.lastEditedBy = lastEditedBy;
    }

    /**
     * 
     */
    public Set<AttachmentGroup> getAttachmentGroups()
    {
        return this.attachmentGroups;
    }

    public void setAttachmentGroups(Set<AttachmentGroup> attachmentGroups)
    {
        this.attachmentGroups = attachmentGroups;
    }

    /**
     * 
     */
    public Set<AttachmentMetadata> getMetadata()
    {
        return this.metadata;
    }

    public void setMetadata(Set<AttachmentMetadata> metadata)
    {
        this.metadata = metadata;
    }

}
