package edu.ku.brc.specify.datamodel;

import java.util.Date;
import java.util.Set;




/**
 * ExternalResource generated by hbm2java
 */
public class ExternalResource  implements java.io.Serializable {

    // Fields    

     protected Integer externalFileId;
     protected String mimeType;
     protected String fileName;
     protected Integer fileCreatedDate;
     protected String remarks;
     protected String externalLocation;
     protected Date timestampCreated;
     protected Date timestampModified;
     protected String lastEditedBy;
     protected Set extResAttrs;
     private Agent createdByAgent;
     private Set agents;
     private Set collectionObjects;
     private Set collectinEvents;
     private Set loans;
     private Set localities;
     private Set permits;
     private Set preparations;
     private Set taxonomy;


    // Constructors

    /** default constructor */
    public ExternalResource() {
    }
    
    /** constructor with id */
    public ExternalResource(Integer externalFileId) {
        this.externalFileId = externalFileId;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getExternalFileId() {
        return this.externalFileId;
    }
    
    public void setExternalFileId(Integer externalFileId) {
        this.externalFileId = externalFileId;
    }

    /**
     *      *            @hibernate.property
     *             column="MimeType"
     *             length="32"
     *         
     */
    public String getMimeType() {
        return this.mimeType;
    }
    
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    /**
     *      *            @hibernate.property
     *             column="FileName"
     *             length="128"
     *         
     */
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     *      *            @hibernate.property
     *             column="FileCreatedDate"
     *             length="10"
     *         
     */
    public Integer getFileCreatedDate() {
        return this.fileCreatedDate;
    }
    
    public void setFileCreatedDate(Integer fileCreatedDate) {
        this.fileCreatedDate = fileCreatedDate;
    }

    /**
     *      *            @hibernate.property
     *             column="Remarks"
     *             length="1073741823"
     *         
     */
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     *      *            @hibernate.property
     *             column="ExternalLocation"
     *             length="1024"
     *         
     */
    public String getExternalLocation() {
        return this.externalLocation;
    }
    
    public void setExternalLocation(String externalLocation) {
        this.externalLocation = externalLocation;
    }

    /**
     *      *            @hibernate.property
     *             column="TimestampCreated"
     *             length="23"
     *         
     */
    public Date getTimestampCreated() {
        return this.timestampCreated;
    }
    
    public void setTimestampCreated(Date timestampCreated) {
        this.timestampCreated = timestampCreated;
    }

    /**
     *      *            @hibernate.property
     *             column="TimestampModified"
     *             length="23"
     *         
     */
    public Date getTimestampModified() {
        return this.timestampModified;
    }
    
    public void setTimestampModified(Date timestampModified) {
        this.timestampModified = timestampModified;
    }

    /**
     *      *            @hibernate.property
     *             column="LastEditedBy"
     *             length="50"
     *         
     */
    public String getLastEditedBy() {
        return this.lastEditedBy;
    }
    
    public void setLastEditedBy(String lastEditedBy) {
        this.lastEditedBy = lastEditedBy;
    }

    /**
     *      *            @hibernate.set
     *             lazy="true"
     *             inverse="true"
     *             cascade="delete"
     *            @hibernate.collection-key
     *             column="ExtResAttrsID"
     *            @hibernate.collection-one-to-many
     *             class="edu.ku.brc.specify.datamodel.ExtResAttrs"
     *         
     */
    public Set getExtResAttrs() {
        return this.extResAttrs;
    }
    
    public void setExtResAttrs(Set extResAttrs) {
        this.extResAttrs = extResAttrs;
    }

    /**
     *      *            @hibernate.many-to-one
     *             not-null="true"
     *            @hibernate.column name="MadeByID"         
     *         
     */
    public Agent getCreatedByAgent() {
        return this.createdByAgent;
    }
    
    public void setCreatedByAgent(Agent createdByAgent) {
        this.createdByAgent = createdByAgent;
    }

    /**
     * 
     */
    public Set getAgents() {
        return this.agents;
    }
    
    public void setAgents(Set agents) {
        this.agents = agents;
    }

    /**
     * 
     */
    public Set getCollectionObjects() {
        return this.collectionObjects;
    }
    
    public void setCollectionObjects(Set collectionObjects) {
        this.collectionObjects = collectionObjects;
    }

    /**
     * 
     */
    public Set getCollectinEvents() {
        return this.collectinEvents;
    }
    
    public void setCollectinEvents(Set collectinEvents) {
        this.collectinEvents = collectinEvents;
    }

    /**
     * 
     */
    public Set getLoans() {
        return this.loans;
    }
    
    public void setLoans(Set loans) {
        this.loans = loans;
    }

    /**
     * 
     */
    public Set getLocalities() {
        return this.localities;
    }
    
    public void setLocalities(Set localities) {
        this.localities = localities;
    }

    /**
     * 
     */
    public Set getPermits() {
        return this.permits;
    }
    
    public void setPermits(Set permits) {
        this.permits = permits;
    }

    /**
     * 
     */
    public Set getPreparations() {
        return this.preparations;
    }
    
    public void setPreparations(Set preparations) {
        this.preparations = preparations;
    }

    /**
     * 
     */
    public Set getTaxonomy() {
        return this.taxonomy;
    }
    
    public void setTaxonomy(Set taxonomy) {
        this.taxonomy = taxonomy;
    }




}