package edu.ku.brc.specify.datamodel;

import java.util.*;




/**
 * RecordSetItem generated by hbm2java
 */
public class RecordSetItem  implements java.io.Serializable {

    // Fields    

     private Integer recordId;


    // Constructors

    /** default constructor */
    public RecordSetItem() {
    }
    
   
    
    

    // Property accessors

    /**
     * 
     */
    public Integer getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }




}