package edu.ku.brc.specify.datamodel;





/**
 * RecordSetItem generated by hbm2java
 */
@SuppressWarnings("serial")
public class RecordSetItem  implements java.io.Serializable {

    // Fields    

     protected String recordId;


    // Constructors

    /** default constructor */
     public RecordSetItem() {
     }
     
     public RecordSetItem(final int recordId) 
     {
    	 this.recordId = Integer.toString(recordId);
     }
     
     public RecordSetItem(final String recordId) 
     {
    	 this.recordId = recordId;
     }
     
   
    
    

    // Initializer
    public void initialize()
    {
        recordId = null;
    }
    // End Initializer

    // Property accessors

    /**
     * 
     */
    public String getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }




    // Add Methods

    // Done Add Methods
}
