package edu.ku.brc.specify.datamodel;





/**
 * RecordSetItem generated by hbm2java
 */
@SuppressWarnings("serial")
public class RecordSetItem  implements java.io.Serializable {

    // Fields    

     protected Long recordId;


    // Constructors

    /** default constructor */
     public RecordSetItem() {
     }
     
     public RecordSetItem(final Long recordId) 
     {
    	 this.recordId = recordId;
     }
     
     public RecordSetItem(final String recordId) 
     {
    	 this.recordId = Long.parseLong(recordId);
     }
     
   
    
    

    // Initializer
    public void initialize()
    {
        recordId = null;
    }
    // End Initializer

    // Property accessors

    /**
     * 
     */
    public Long getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(final Long recordId) {
        this.recordId = recordId;
    }




    // Add Methods

    // Done Add Methods
}
