 package edu.ku.brc.specify.ui.db;

import java.util.Date;


/**
 * PickListItem generated by hbm2java
 */
@SuppressWarnings("serial")
public class PickListItem  implements java.io.Serializable, Comparable<PickListItem> {

    // Fields

     private String title;
     private String value;
     private Date createdDate;


    // Constructors

    /** default constructor */
    public PickListItem() 
    {
        
    }

    // Property accessors

    public PickListItem(String title, String value, Date createdDate)
    {
        super();
        this.title = title;
        this.value = value;
        this.createdDate = createdDate;
    }

    /**
     *
     */
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    /**
     *
     */
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public int compareTo(PickListItem obj)
    {
        if (title.equals(obj.title))
        {
            return 0;

        } else
        {
           return title.compareTo(obj.title);
        }
    }

    public String toString()
    {
        return title;
    }

    /**
     *
     */
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

}