
package edu.ku.brc.services.geolocate.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b59-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "geolocatesvc", targetNamespace = "http://www.museum.tulane.edu/webservices/", wsdlLocation = "http://www.museum.tulane.edu:8080/webservices/geolocatesvc/geolocatesvc.asmx?wsdl")
public class Geolocatesvc
    extends Service
{

    private final static URL GEOLOCATESVC_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://www.museum.tulane.edu:8080/webservices/geolocatesvc/geolocatesvc.asmx?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        GEOLOCATESVC_WSDL_LOCATION = url;
    }

    public Geolocatesvc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Geolocatesvc() {
        super(GEOLOCATESVC_WSDL_LOCATION, new QName("http://www.museum.tulane.edu/webservices/", "geolocatesvc"));
    }

    /**
     * 
     * @return
     *     returns GeolocatesvcSoap
     */
    @WebEndpoint(name = "geolocatesvcSoap")
    public GeolocatesvcSoap getGeolocatesvcSoap() {
        return (GeolocatesvcSoap)super.getPort(new QName("http://www.museum.tulane.edu/webservices/", "geolocatesvcSoap"), GeolocatesvcSoap.class);
    }

}
