package edu.ku.brc.specify.extfilerepos.impl;

import java.util.*;




/**
 * ExternalFileEntry generated by hbm2java
 */
@SuppressWarnings("serial")
public class ExternalFileEntry  implements java.io.Serializable {

    // Fields    

     private Long id;
     private String name;
     private String descr;
     private String mimeType;
     private String path;
     private Date created;


    // Constructors

    /** default constructor */
    public ExternalFileEntry() {
    }
    
    /** constructor with id */
    public ExternalFileEntry(Long id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * 
     */
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 
     */
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     */
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * 
     */
    public String getMimeType() {
        return this.mimeType;
    }
    
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    /**
     * 
     */
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * 
     */
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }




}